pipeline {
    
    agent any
// zak commented this lines to be able to run the pipeline
//    agent {
//        docker {
//            image 'maven:3.9.0'
//            args '-v /root/.m2:/root/.m2'
//        }
//    }

    options {
        ansiColor('xterm')
    }


    stages {
        stage('Test color') {
            steps {
                echo '\033[34mHello\033[0m \033[33mcolorful\033[0m \033[35mworld!\033[0m'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }

        stage("PipeLine Completed"){
            steps{
                echo "====++++executing PipeLine Completed++++===="
            }
            post{
                // always{
                //     echo "====++++always++++===="
                // }
                success{
                    echo "====++++PipeLine Completed executed successfully++++===="
                }
                failure{
                    echo "====++++PipeLine Completed execution failed++++===="
                }
        
            }
        }
    }
}
